### PR TITLE
removed symbolic link

### PR DESCRIPTION
**Pull request by nilroy**
@pcross616 

We are using kitchen-docker to test our chef cookbooks. The symbolic link used in this cookbook is breaking all our tests as kitchen-docker is failing to upload these symbolic links. I think these data bags are quite static and we don't change them much. So it should not matter much

### CODE REVIEW

**Comment by nilroy** [comment]
@pcross616 can we merge this PR?

**Comment by bpcook61** [comment]
There have been numerous test builds done with kitchen-docker that completed successfully with the symbolic link.  (https://travis-ci.org/sous-chefs/rundeck/builds/208771853)  I question whether this is actually causing the test failures you are seeing.

**Comment by ev0ldave** [comment]
@nilroy The team has left webtrends and we have now transferred this repository over to sous-chefs to breath new life into this cookbook.  Feel free to apply to the group if you'd like to help maintain it

**Comment by ev0ldave** [comment]
thanks @nilroy this was factored in and fixed, closing

**Pull request closed without merging**
