### PR TITLE
Make rdbms data bag optional

### LINKED ISSUE #98: If rdbms data bag not present, cookbook errors out
When using node attributes for rdbms, the cookbook fails out saying "404 not found" as it is trying to load a data bag which does not exist. We should still use the node attributes if the data bag doesn't exist.

### PR DESCRIPTION
**Pull request by gsreynolds**
### Description

If rdbms data bag does not exist, use the dbuser and dbpassword from attributes

### Issues Resolved

Fix #98

### Contribution Check List

- [ ] All tests pass.
- [ ] New functionality includes testing.
- [ ] New functionality has been documented in the README if applicable

---
This change is [Reviewable](https://reviewable.io/reviews/sous-chefs/rundeck/179)

### CODE REVIEW

**Comment by gsreynolds** [comment]
Do we perhaps need to add tests for the with/without data bag logic? Maybe just a ChefSpec?

**Comment by nilroy** [comment]
@gsreynolds It would be good to have those tests in place

**Comment by gsreynolds** [comment]
Travis failures in latest commit are due to rundeck_api_client library loading in serverspec testing (kitchen-vagrant vs kitchen-dokken locations in serverspec spec_helper.rb), so unrelated to PR. Not sure why between 8def37ee6a8143564dd6ffb67018e86aa7265022 that was green and 5898717bbc7b4b2c4df13477d746e4a796ee67ca those jobs are failing though...

UNIT_AND_LINT job was successful however: https://travis-ci.org/sous-chefs/rundeck/jobs/271993370

**Comment by gsreynolds** [comment]
Rebased branch from master, changes from #177 caused conflicts in `recipes/_data_bags.rb`

**Comment by ev0ldave** [comment]
Reviewed 4 of 4 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sous-chefs/rundeck/179)*

**Comment by damacus** [comment]
@gsreynolds we can probably get this merged in sometime soon with the uni test fixes.

**Comment by damacus** [comment]
If this is still needed please reopen 👍

**Pull request closed without merging**
