### PR TITLE
Adds support for support for specifying ACL Policies via Ruby Hash

### PR DESCRIPTION
**Pull request by PowerSchill**
### Description

~~Instead of using a pure Ruby hash and template to create ACL policies it switches to a hash of the actual contents of the ACL policy. This was done due to the amount of logic required for composing the actual policy on disk.~~ Converts the Ruby hash into yaml for creation of ACL policy file.

### Issues Resolved

[List any existing issues this PR resolves]

### Contribution Check List

- [ ] All tests pass.
- [ ] New functionality includes testing.
- [ ] New functionality has been documented in the README if applicable

### CODE REVIEW

**Comment by kitchen-porter** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          2 Errors
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Please add labels to this Pull Request</td>
    </tr>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Please include a <a href="https://github.com/sous-chefs/line-cookbook/blob/master/CHANGELOG.md">CHANGELOG</a> entry.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by mengesb** [comment]
Not sure if this is a dead PR or not; but I've noticed that Rundeck's ACL engine is very YAML ... so why not simply generate ACLs via `.to_hash.to_yaml` ?

**Comment by PowerSchill** [comment]
I don't think it was the format that was giving me an issue but the logic. I was attempting to use a Ruby Hash to create the template but there was some part of the logic I couldn't get to fit within the template structure. Can't remember the issue at the moment. I decided to just use the string since it is the easiest and you can actually check the syntax within Rundeck.

**Comment by mengesb** [comment]
I can see that the template is a little left to be desired.

If we want to force the user to do two generations of ACLs and use `to_yaml`, we could go with something like:

```ruby
{
  description: "Admin, all access.",
  context: {
    project: '.*',
  },
  for: {
    resource: [
      { allow: '*', },
    ],
    adhoc: [
      { allow: '*', },
    ],
    job: [
      { allow: '*', },
    ],
    nodes: [
      { allow: '*', },
    ],
  },
  by: {
    group: 'admin',
  },
}
```

The above would cover the project' context of the admin policy. There would also have to be the application context.

Looking at the template, I think this would be the default admin acl in ruby that would satisify that template:

```ruby
{
  admin: {
    contexts: [
      {
        description: 'Admin, all access.'
        context: {
          project: '.*'
        },
        for: {
          resource: [
            { allow: '*' },
          ],
          adhoc: [
            { allow: '*' },
          ],
          job: [
            { allow: '*' },
          ],
          node: {
            { allow: '*' },
          }
        },
        by: {
          group: 'admin',
        },
      },
      {
        description: 'Admin, all access.'
        context: {
          application: '.*'
        },
        for: {
          resource: [
            { allow: '*' },
          ],
          project: [
            { allow: '*' },
          ],
          project_acl: [
            { allow: '*' },
          ],
          storage: {
            { allow: '*' },
          }
        },
        by: {
          group: 'admin',
        },
      },
    ],
  },
}
```

**Comment by PowerSchill** [comment]
@mengesb working on your suggestion but I am unsure how to use a Ruby hash to end up with the following yaml structure:

```yaml
 allow: [read,create,update,refresh]
```

**Comment by PowerSchill** [comment]
> 🤔 any chance we can get that test working rather than commenting it out?
> 
> It just looks like it's trying to use a helper or something hasn't been fully loaded, but it shouldn't be too far from being able to be fixed

That's a bigger effort. The current project resource is a carryover from the previous version and requires databags. It is probably the next area I need to address.

**Comment by damacus** [comment]
Probably worth just deleting the whole unit test then 👍

**Pull request merged**
